name: Build
on: [pull_request, push]
jobs:
  build-psp:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: Build for PSP
        run: |
          psp-cmake -B build-psp
          make -C build-psp

      - name: Upload for PSP
        uses: actions/upload-artifact@v4
        with:
          name: EBOOT.PBP
          path: build-psp/EBOOT.PBP
