name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev g++-mingw-w64-i686

      - name: Build for Ubuntu
        run: |
          cmake -B build-ubuntu
          cmake --build build-ubuntu

      - name: Upload for Ubuntu
        uses: actions/upload-artifact@v4
        with:
          name: GravityDefied
          path: build-ubuntu/GravityDefied

  build-psp:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build for PSP
        run: |
          apk add cmake pkgconf sdl2-dev sdl2_image-dev sdl2_ttf-dev
          psp-cmake -B build-psp
          make -C build-psp

      - name: Upload for PSP
        uses: actions/upload-artifact@v4
        with:
          name: EBOOT.PBP
          path: build-psp/EBOOT.PBP
