name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Workaround Git Permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build for PSP
        run: |
          export PATH=/usr/local/pspdev/bin:$PATH
          psp-cmake -B build-psp
          make -C build-psp

      - name: Upload for PSP
        uses: actions/upload-artifact@v4
        with:
          name: GravityDefied-PSP
          path: build-psp/EBOOT.PBP
